import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainLayout from "@/components/layout/MainLayout";
import SurahSidebar from "@/components/SurahSidebar";
import { SettingsProvider } from "@/context/SettingsContext";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const surahs = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/surahs`).then(
    (res) => res.json(),
  );
  // console.log(surahs[0]);
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body >
        <SettingsProvider>
          <Header />
          <div className="flex h-screen  text-white overflow-hidden">
            {/* 1. Left Icon Sidebar (Fixed) */}
            <aside>
              <SurahSidebar surahs={surahs} />
            </aside>
            {/* 2. Main Area (Scrollable) */}
            <main className="flex-1 overflow-y-auto relative">{children}</main>
          </div>
        </SettingsProvider>
      </body>
    </html>
  );
}
